# This file is automatically generated by 'gen-command' command in Makefile.
# Don't edit this file manually.
# Run the module's apis.

method_:
		/home/mohsen/envs/py/carotid-plaque/env_home_linux_3.11/bin/python api/method_.py
